### ISSUE TITLE
Cannot save level progress

### ISSUE THREAD

**Issue by maouzju** [pancelor/PuzzleScript#8]
The document says :
The level names (in this case, "intro1" and "tricky_variant_2") are optional, but will help persist players' save data in the level select menu if you update your game and rearrange the levels. These level names are internal-only, and are never shown to the player.

I used LEVEL_SELECT_POINT and enable_level_select.
The level select function is correct, 
But when I update new html file to itch, the save data is gone.

**Comment by maouzju** [comment]
title Golem's Expedition 
author maou
homepage https://maougame.itch.io/
enable_level_select

========
OBJECTS
========

Background
green yellow 
11111
11111
11111
11111
11111



Water
lightBlue white
00010
10001
00100
10010
00000


cutter
red white
.111.
11111
10001
11111
.111.

Wall
black DARKBROWN
.11..
.111.
11011
11110
10000

Player
Black Orange White Blue
.000.
.000.
00000
00000
.0.0.


CrateWin
Orange lightgreen
.000.
01110
01110
01110
.000.

crateBridge
brown gray lightblue darkblue
21112
13331
13331
13331
21112

pole 
Orange brown lightblue darkblue white darkgreen 
..4..
..4..
..4..
.....
.....

 

crateBridgeTemp
brown gray lightblue darkblue
21112
13231
12221
13231
21112

Crate
Orange brown
.000.
01110
01110
10001
.111.

CrateL
Orange
00000
0...0
0...0
0...0
00000

CrateR
Orange
00000
0...0
0...0
0...0
00000

CrateU
Orange
00000
0...0
0...0
0...0
00000

CrateD
Orange
00000
0...0
0...0
0...0
00000


CrateStop
Orange
00000
0...0
0...0
0...0
00000


target
red
.0000
.000.
.00..
.0...
.0...

playerCrateBridge
white
.....
.....
.....
.....
.....

crateBridgeMoveL
white
.....
.....
.....
.....
.....
crateBridgeMoveR
white
.....
.....
.....
.....
.....
crateBridgeMoveU
white
.....
.....
.....
.....
.....
crateBridgeMoveD
white
.....
.....
.....
.....
.....


pole_
white
.....
.....
.....
.....
.....
=======
LEGEND
=======

. = Background
# = Wall
P = Player
* = Crate
G = CRATE AND POLE

t = target

s = wall and  water

w = water

o = crate and Water

c = cutter

l = cutter and water

b = crateBridge
d = crateBridge and pole

crates = Crate or cratel or crater or crateu or crated or CrateStop


bridgeCannotMoveTo = wall 

crateBridgeObjects = crateBridge 

crateBridgeMove = crateBridgeMoveu or crateBridgeMoved or crateBridgeMoveL or crateBridgeMoveR
=======
SOUNDS
=======

player move 83799907
sfx0 36772507
sfx1 44210101
sfx2 22002302
SFX3 16183907
endlevel 36576503

sfx9 88563502

================
COLLISIONLAYERS
================

Background
water,crateBridge,target,CRATEBRIDGETEMP


crateBridgeMoveL,crateBridgeMover,crateBridgeMoveu,crateBridgeMoved
cutter
playerCrateBridge
Crate, Crated, Crateu, Cratel, CrateR,CrateStop,CrateWin
Player, Wall

pole
pole_
======
RULES
======


(记录玩家当前所在的船)
[playerCrateBridge] -> []
[Player crateBridge] ->[Player crateBridge playerCrateBridge]
[playerCrateBridge|crateBridge]->[playerCrateBridge|crateBridge playerCrateBridge]



[> Player|water]->cancel

[> Player|crateBridge pole]->cancel




left [ >  Player|Crates no Water] -> [  >  Player|CrateL  ]
right [ >  Player|Crates no Water] -> [  >  Player| CrateR  ]
up [ >  Player|Crates no Water] -> [  >  Player| CrateU  ]
down [ >  Player|Crates no Water] -> [  >  Player| CrateD  ]


late [CrateL|Crates]->[CrateL|CrateL] 
late [CrateR|Crates]->[CrateR|CrateR] 
late [CrateU|Crates]->[CrateU|CrateU] 
late [CrateD|Crates]->[CrateD|CrateD] 
late [CrateL|Crates]->[CrateL|CrateL] 
late [CrateR|Crates]->[CrateR|CrateR] 
late [CrateU|Crates]->[CrateU|CrateU] 
late [CrateD|Crates]->[CrateD|CrateD] 
late [CrateL|Crates]->[CrateL|CrateL] 
late [CrateR|Crates]->[CrateR|CrateR] 
late [CrateU|Crates]->[CrateU|CrateU] 
late [CrateD|Crates]->[CrateD|CrateD] 
late [CrateL|Crates]->[CrateL|CrateL] 
late [CrateR|Crates]->[CrateR|CrateR] 
late [CrateU|Crates]->[CrateU|CrateU] 
late [CrateD|Crates]->[CrateD|CrateD] 
late [CrateL|Crates]->[CrateL|CrateL] 
late [CrateR|Crates]->[CrateR|CrateR] 
late [CrateU|Crates]->[CrateU|CrateU] 
late [CrateD|Crates]->[CrateD|CrateD] 



(船可以被方块推动)
late left [CrateL|crateBridge pole playerCrateBridge]-> cancel 
late left [CrateL|wall]-> [CrateStop|wall]cancel
late [CrateL|CrateStop]-> [CrateStop|CrateStop]cancel
late left [CrateL pole|]->[CrateL|pole_]
late left [CrateL|crateBridge pole no playerCrateBridge]-> [|CrateStop crateBridge pole crateBridgeMoveL]
late left [CrateL|no crates no wall]->  [|CrateStop] SFX0


late RIGHT [CrateR|crateBridge pole playerCrateBridge]-> cancel 
late RIGHT [CrateR|wall]-> [CrateStop|wall]cancel
late [CrateR|CrateStop]->[CrateStop|CrateStop] cancel
late RIGHT [CrateR pole|]->[CrateR|pole_]
late RIGHT [CrateR|crateBridge pole no playerCrateBridge]-> [|CrateStop crateBridge pole crateBridgeMoveR]
late RIGHT [CrateR|no crates no wall]->  [|CrateStop]  SFX0


late UP [CrateU|crateBridge pole playerCrateBridge]-> cancel 
late UP [CrateU|wall]-> [CrateStop|wall]cancel
late [CrateU|CrateStop]->[CrateStop|CrateStop] cancel
late UP [CrateU pole|]->[CrateU|pole_]
late UP [CrateU|crateBridge pole no playerCrateBridge]-> [|CrateStop crateBridge pole crateBridgeMoveU]
late UP [CrateU|no crates no wall]->  [|CrateStop]  SFX0

late DOWN [CrateD|crateBridge pole playerCrateBridge]-> cancel 
late DOWN [CrateD|wall]->[CrateStop|wall]cancel
late [CrateD|CrateStop]->[CrateStop|CrateStop] cancel
late DOWN [CrateD pole|]->[CrateD|pole_]
late DOWN [CrateD|crateBridge pole no playerCrateBridge]-> [|CrateStop crateBridge pole crateBridgeMoveD]
late DOWN [CrateD|no crates no wall]->  [|CrateStop]  SFX0


late [Player crates] -> cancel

late[Crates]->[Crate]


(结算推动船杆)
late [crateBridgeMove | crateBridgeObjects]->[crateBridgeMove|crateBridgeMove crateBridgeObjects]

LATE LEFT [crateBridgeObjects crateBridgeMoveL| bridgeCannotMoveTo] -> cancel
LATE RIGHT [crateBridgeObjects crateBridgeMoveR| bridgeCannotMoveTo] -> cancel
LATE UP [crateBridgeObjects crateBridgeMoveU| bridgeCannotMoveTo] -> cancel
LATE DOWN [crateBridgeObjects crateBridgeMoveD| bridgeCannotMoveTo] -> cancel

LATE LEFT [crateBridgeObjects crateBridgeMoveL| no water no crateBridgeObjects ] -> cancel
LATE RIGHT [crateBridgeObjects crateBridgeMoveR|  no water no crateBridgeObjects] -> cancel
LATE UP [crateBridgeObjects crateBridgeMoveU|  no water no crateBridgeObjects] -> cancel
LATE DOWN [crateBridgeObjects crateBridgeMoveD|  no water no crateBridgeObjects] -> cancel


late LEFT [crateBridgeMoveL pole|]->[crateBridgeMoveL|pole_] SFX3
late RIGHT [crateBridgeMoveR pole|]->[crateBridgeMoveR|pole_]SFX3
late UP [crateBridgeMoveU pole|]->[crateBridgeMoveU|pole_]SFX3
late DOWN [crateBridgeMoveD pole|]->[crateBridgeMoveD|pole_]SFX3

LATE LEFT [crateBridge  crateBridgeMoveL| no crateBridge] -> [ water|crateBridge   ]
LATE right [crateBridge  crateBridgeMoveR| no crateBridge] -> [ water|crateBridge   ]
LATE up [crateBridge  crateBridgeMoveU| no crateBridge] -> [ Water|crateBridge   ]
LATE down [crateBridge  crateBridgeMoveD| no crateBridge] -> [ water|crateBridge   ]


late [pole_]->[pole]


late[crate pole cutter]-> []sfx2
late[crate no pole cutter]-> []sfx2


late[crateBridge pole cutter]-> [Water]sfx2
late[crateBridge no pole cutter]-> [Water]sfx2





late [crate water]->[ crateBridgeTemp]

late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]
late [crate| crateBridgeTemp]->[ crate | crate water]



late[crateBridgeTemp]->[crateBridge] sfx1



==============
WINCONDITIONS
==============

all player on target

=======
LEVELS
=======


LEVEL_SELECT_POINT basic_intro
message level 1
wwwwwwww
w...wwww
w.s..*pw
w....*.w
ww....ww
twswwwww


LEVEL_SELECT_POINT combine_intro
message level 2
wwwwwwwww
wwwwwwwww
wwww..www
www*p..ww
ww...*.ww
ww...wwww
wwwwwwwww
wwwwwwtww

LEVEL_SELECT_POINT pull_intro
message level 3 pull
wwwwwwwww
wwwwwwwww
ww.....ww
ww.*p..ww
ww...**ww
ts...wwww
wwwwwwwww
wwwwwwwww

LEVEL_SELECT_POINT make_a_seven
message level 4 
wwwwwwwwwwwwww
wwwwwwwwwwwwww
www......wwwww
www**..*.wwwww
ww....p*#wwwww
ww......#wwwww
wwwwww..wwwwww
wwwwwwwwwswwww
wwwwwwwwwwwwww
wwwwwwwww....t



LEVEL_SELECT_POINT make_it_straight
message level 5
wwwwwwwwwwwwwwwwww
wwwwwwwwwwww..wwst
www.......ww..wws.
www**.p***ww..wws.
ww........ww..www.
ww........ww.wwww.
wwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwww



LEVEL_SELECT_POINT make_a_hook
message level 6
tssssssssssssss
..wwww***oowwws
.wwwww......wws
wwwwsw.*.**...s
wwwwww..p...w.s
wwwwwwwwww....s
wwwwwwwwwwwwwws
wwwwwwwwwwwwwws



LEVEL_SELECT_POINT make_a_groove 
message level 7
wwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwww
wwwwwww........wwwwwwww
wwwwwww.wwwww..wwwwwwww
wwwwwww...www.....**.ww
wwwwwwwww.www....p*..ww
wwwwww....www...*....ww
wwwwww.wwwwww..**.**.ww
wwwtw..wwwwww........ww
wwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwww
wwwwwwwwwwwwwwwwwwwwwww

LEVEL_SELECT_POINT choose_groove_position 
message level 8
wwwwwwwwwwss#sssssss
wwwwwwwwwwswwwwwwwws
ssssssssssswwwwwwwws
s.**wwwwwts........s
s.*wwwww##s........s
s.*.wwwwwww.***....s
s.swwwwwwww........s
s.swwwwwww#.***..p.s
s.swwwwwww#........s
s.ssssssss#.***....s
s..................s
ssssssssssssssssssss




LEVEL_SELECT_POINT fill_up_the_lake  
message level 9
#####################
###################t#
#.*................w#
#wowwwwwwwwwwwwwwwww#
#.*................w#
#.*........**..**..w#
#.*..wwww...*..*...w#
#.*..wwww...*..*...w#
#.*..wwww........p.w#
#.*........**......w#
#.*........**.****.w#
#.*................w#
#.*................w#
#...#################




LEVEL_SELECT_POINT cutter_intro
message level 10
##############
#twww...*....#
#wwww...*....#
#www..c.*....#
#www....*..p.#
#www....*....#
#www.........#
#www.........#
##############


LEVEL_SELECT_POINT cutter_make_a_shape
message level 11
ssssss###############
s#wwww#.............#
stw.ww#.............#
ssswww#.............#
ssswww...***.c.c....#
ssswww...*.*........#
sswwww...*.*........#
sswwww...***........#
sswwww..p...........#
sswwww............###
sswwwwwwwwwwwwwwwwwww
sswwwwwwwwwwwwwwwwwww
sswwwwwwwwwwwwwwwwwww
sssssssssssssssssssss


LEVEL_SELECT_POINT cutter_make_a_pull
message level 12
############www
#..........swww
#........p.swww
#....c.....swww
#......***.ssss
#..c...***..*ts
#......***..*.s
#....c.***..*.s
#...........*.s
############sss



LEVEL_SELECT_POINT pole_intro
message level 13
sssssssss
wwwwww###
wwwwww#t#
wwwwww#.#
wwwwbwwws
.*..dwww#
.*.wbwww#
.*.....##
.........
..p......


LEVEL_SELECT_POINT make_a_shape_to_push_pole 
message level 14
wbbbbb###
wdwwww.t#
wb....###
ww......s
........#
.*..**..#
.**..*..#
.........
..p......


LEVEL_SELECT_POINT manage_bridge_order
message level 15

#############
#...#.......#
#wwwwwwwwwww#
#wwwwwwwwwww#
#t#..*.*.g..#
###..*.*.g.p#
..#.........#
..###########


LEVEL_SELECT_POINT cut_a_pole_to_make_a_way
message level 16
###############
#........ssssts
#.g*g..*.wwwwww
#.**g....wwwwww
#........ssssss
#.**g..c......#
#.gg*.........#
#.....p.......#
#.............#
###############



LEVEL_SELECT_POINT push_the_boat_by_a_long_strip
message level 17

###ssssswwwww
#t#wwwwswwwww
#..wwwwswwwww
#..swwwswwwww
#..swwwswwwww
#..swwwswwwww
#..swwwssssss
###swww#....#
#........*..#
#.*g...*.*..#
#....p.*.*..#
#.**...*.*..#
#...........#
#...........#
#############


LEVEL_SELECT_POINT make_a_square_then_push
message level 18

wwwwwwst#####
wwwwww#.#####
ssssss#..####
#..wwwwwwww##
#..wwwwwwww##
#..wwwwwwww.#
*..wwwwwwww.#
*......ssss.#
*...gg..g*..#
*....g...*.##
*....*...*.##
*...g...g..##
*...g.p.*..##
*...gg..gg.##
*..........##
*.*........##
***........##
#############



LEVEL_SELECT_POINT a_pole_pusher_on_both_sides_of_the_river  
message level 19

#########.........
#..www.t#.........
#..www###.........
#..www..#.........
#..www..#.........
#..www..#.........
#..www..#.........
###www..#.........
#..www..#.........
#..www..##########
#..www..#........#
#..www..#.**..*..#
#..www###.....g..#
#..www....**....p#
#..www...........#
#..www....**.....#
#..#.............#
##################






(
sssssssssssssssss
swww...t........s
swwwwwwwwwwwwwwws
swwwwwwwwwwwwwwws
swwwwwsswwwwwwwws
swwwwwsswwwwwwwws
swwwwwsswwwwwwwws
swwwwwwwwwwwwwwws
swwwwwwwwwwwwwwws
swwwwwwwwwooowwws
swwwwwwwwwwwowwws
s.....c.....*...s
#...........*...s
#.........***...s
#.........*.....s
#.........*.....s
#.........*...p.#
#.........***...#
#...............#
#################

)



message That's it, well done.

**Comment by pancelor** [comment]
hey! sorry I missed this for so long. the issue was that separate itch uploads are uploaded to different URLs, which was messing up the save data system. It should be fixed now!

edit: it seems like you need to enter and exit a level after a new upload before the solved marks appear? strange; I'll look into it later
